name: Publish image and deploy the application to EKS
on:
  workflow_dispatch:

jobs:
  build:
    name: build, publish, deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish image
        id: publish
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          args: publish --aws-access-key-id=env://AWS_ACCESS_KEY_ID --aws-secret-access-key=env://AWS_SECRET_ACCESS_KEY
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}

      - name: Deploy to K8S
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: dagger/dagger-for-github@v7
        with:
          version: "latest"
          verb: call
          args: deploy --image=${{ steps.publish.outputs.output }} --aws-access-key-id=env://AWS_ACCESS_KEY_ID --aws-secret-access-key=env://AWS_SECRET_ACCESS_KEY --cluster-name ${{ vars.CLUSTER_NAME }}
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
