name: Deploy

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      deploy-tag:
        description: Enter the tag to deploy
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext
          curl -o kubectl https://dl.k8s.io/release/v1.31.0/bin/linux/amd64/kubectl
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract tag version
        id: extract_tag
        shell: bash
        run: |
          if [ -n "${{ github.event.inputs.deploy-tag }}" ]; then
            echo "TAG_VERSION=${{ github.event.inputs.deploy-tag }}" >> $GITHUB_ENV
          else
            echo "TAG_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          fi
      - name: Build and push Docker image to ECR
        env:
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/parisjug-dagger-demo/translate-api:${{ env.TAG_VERSION }}
        run: |
          docker build -f src/main/docker/Dockerfile.jvm --platform linux/amd64 -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: update kube config
        run: |
          aws eks --region ${{ secrets.AWS_REGION }} update-kubeconfig --name confused-classical-sheepdog

      - name: deploy application to EKS
        env:
          IMAGE_URI: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/parisjug-dagger-demo/translate-api:${{ env.TAG_VERSION }}
        run: |
          envsubst < src/main/kube/app.yaml | kubectl apply -f -

      - name: Logout from Amazon ECR
        run: docker logout ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com
