name: Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'Release version'
        required: true
      development-version:
        description: 'Next development version'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set up SSH for GitHub
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Maven Release
        run: |
          mvn -B release:clean release:prepare \
              -DreleaseVersion=${{ github.event.inputs.release-version }} \
              -DdevelopmentVersion=${{ github.event.inputs.development-version }} \
              -DpushChanges=true
